import type { PopularAuthor, Story } from "@/lib/types"

export const sampleStories: Story[] = [
  {
    id: "1",
    title: "별빛 아래에서 시작된 여정",
    genre: "판타지",
    tags: ["모험", "마법", "우정"],
    likes: 234,
    turns: 15,
    preview:
      "그날 밤, 하늘에서 떨어진 것은 별이 아니었다. 소녀는 숲 속 깊은 곳에서 빛나는 무언가를 발견했다...",
    isChallenge: true,
  },
  {
    id: "2",
    title: "2087년, 서울의 마지막 날",
    genre: "SF",
    tags: ["디스토피아", "AI", "생존"],
    likes: 189,
    turns: 12,
    preview: "도시는 이미 텅 비어 있었다. 남은 것은 녹슨 드론들과 잊혀진 기억뿐...",
  },
  {
    id: "3",
    title: "우연히, 카페에서",
    genre: "로맨스",
    tags: ["일상", "첫사랑", "재회"],
    likes: 312,
    turns: 23,
    preview: "10년 만에 다시 마주친 그 사람. 커피 한 잔이 모든 것을 바꿔놓을 줄은 몰랐다...",
  },
  {
    id: "4",
    title: "13층에서 들리는 소리",
    genre: "공포",
    tags: ["미스터리", "심령", "아파트"],
    likes: 156,
    turns: 8,
    preview: "이 건물에는 13층이 없다고 했다. 하지만 매일 밤 12시가 되면...",
  },
  {
    id: "5",
    title: "할머니의 비밀 레시피",
    genre: "자유",
    tags: ["가족", "요리", "추억"],
    likes: 278,
    turns: 18,
    preview: "오래된 수첩에 적힌 레시피. 재료 목록 마지막에는 이상한 문장이 적혀 있었다...",
  },
  {
    id: "6",
    title: "용의 심장을 가진 기사",
    genre: "판타지",
    tags: ["기사", "용", "전쟁"],
    likes: 203,
    turns: 21,
    preview: "그는 용을 죽이러 갔다가, 대신 용의 심장을 얻어 돌아왔다...",
  },
]

export const popularAuthors: PopularAuthor[] = [
  {
    id: "1",
    name: "별지기",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=star",
    storiesCount: 12,
    totalLikes: 1523,
    totalTurns: 45,
    badge: "전설 작가",
  },
  {
    id: "2",
    name: "숲의여행자",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=forest",
    storiesCount: 8,
    totalLikes: 892,
    totalTurns: 34,
    badge: "베테랑 작가",
  },
  {
    id: "3",
    name: "달빛작가",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=moon",
    storiesCount: 15,
    totalLikes: 2104,
    totalTurns: 67,
    badge: "전설 작가",
  },
  {
    id: "4",
    name: "새벽이슬",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=dawn",
    storiesCount: 6,
    totalLikes: 645,
    totalTurns: 23,
    badge: "인기 작가",
  },
  {
    id: "5",
    name: "시간여행자",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=time",
    storiesCount: 10,
    totalLikes: 1234,
    totalTurns: 52,
    badge: "베테랑 작가",
  },
  {
    id: "6",
    name: "은하수탐험",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=galaxy",
    storiesCount: 7,
    totalLikes: 789,
    totalTurns: 29,
    badge: "인기 작가",
  },
]

